//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStuff11net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_SaveDirectory {
            get {
                return ((string)(this["Last_SaveDirectory"]));
            }
            set {
                this["Last_SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Last_CreateDriverDirectory {
            get {
                return ((bool)(this["Last_CreateDriverDirectory"]));
            }
            set {
                this["Last_CreateDriverDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DriverResourceUrl {
            get {
                return ((string)(this["DriverResourceUrl"]));
            }
            set {
                this["DriverResourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceManufacturers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceManufacturers"]));
            }
            set {
                this["UserDeviceManufacturers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceInterfaceGUIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceInterfaceGUIDs"]));
            }
            set {
                this["UserDeviceInterfaceGUIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceDescriptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceDescriptions"]));
            }
            set {
                this["UserDeviceDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserSaveDirectorys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserSaveDirectorys"]));
            }
            set {
                this["UserSaveDirectorys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_DriverName {
            get {
                return ((string)(this["Last_DriverName"]));
            }
            set {
                this["Last_DriverName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_VID {
            get {
                return ((int)(this["Last_VID"]));
            }
            set {
                this["Last_VID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_PID {
            get {
                return ((int)(this["Last_PID"]));
            }
            set {
                this["Last_PID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnStateWidth {
            get {
                return ((string)(this["ColumnStateWidth"]));
            }
            set {
                this["ColumnStateWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnAutoSizeMode {
            get {
                return ((string)(this["ColumnAutoSizeMode"]));
            }
            set {
                this["ColumnAutoSizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResizeHorizontal {
            get {
                return ((int)(this["ResizeHorizontal"]));
            }
            set {
                this["ResizeHorizontal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResizeVertical {
            get {
                return ((int)(this["ResizeVertical"]));
            }
            set {
                this["ResizeVertical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ProductionManagement")]
        public string DataBaseAddress {
            get {
                return ((string)(this["DataBaseAddress"]));
            }
            set {
                this["DataBaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataBaseName {
            get {
                return ((string)(this["DataBaseName"]));
            }
            set {
                this["DataBaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The AND operator displays a record if both the first/n condition and the second c" +
            "ondition is true.")]
        public string comboBox_SecondCondition_AND {
            get {
                return ((string)(this["comboBox_SecondCondition_AND"]));
            }
            set {
                this["comboBox_SecondCondition_AND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The OR operator displays a record if either the first/n condition or the second c" +
            "ondition is true.")]
        public string comboBox_SecondCondition_OR {
            get {
                return ((string)(this["comboBox_SecondCondition_OR"]));
            }
            set {
                this["comboBox_SecondCondition_OR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The None operator  do not displays a second condition/n or the second condition d" +
            "ialog.")]
        public string comboBox_SecondCondition_None {
            get {
                return ((string)(this["comboBox_SecondCondition_None"]));
            }
            set {
                this["comboBox_SecondCondition_None"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010-01-01")]
        public global::System.DateTime CalendarPlanerMinDate {
            get {
                return ((global::System.DateTime)(this["CalendarPlanerMinDate"]));
            }
            set {
                this["CalendarPlanerMinDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-01-26")]
        public global::System.DateTime CalendarPlanerMaxDate {
            get {
                return ((global::System.DateTime)(this["CalendarPlanerMaxDate"]));
            }
            set {
                this["CalendarPlanerMaxDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable DataTableSetting {
            get {
                return ((global::System.Data.DataTable)(this["DataTableSetting"]));
            }
            set {
                this["DataTableSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Downloads {
            get {
                return ((bool)(this["Downloads"]));
            }
            set {
                this["Downloads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No set to any department yet")]
        public string DepartmentName {
            get {
                return ((string)(this["DepartmentName"]));
            }
            set {
                this["DepartmentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationsShowMyOwn {
            get {
                return ((bool)(this["NotificationsShowMyOwn"]));
            }
            set {
                this["NotificationsShowMyOwn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationsShowWarnings {
            get {
                return ((bool)(this["NotificationsShowWarnings"]));
            }
            set {
                this["NotificationsShowWarnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifycationsEnableSendReceive {
            get {
                return ((bool)(this["NotifycationsEnableSendReceive"]));
            }
            set {
                this["NotifycationsEnableSendReceive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationsSendMyOwn {
            get {
                return ((bool)(this["NotificationsSendMyOwn"]));
            }
            set {
                this["NotificationsSendMyOwn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProductionInventoryDataSetCaseSensitive {
            get {
                return ((bool)(this["ProductionInventoryDataSetCaseSensitive"]));
            }
            set {
                this["ProductionInventoryDataSetCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitContainerBomFtvSectionSplitterDistance {
            get {
                return ((int)(this["splitContainerBomFtvSectionSplitterDistance"]));
            }
            set {
                this["splitContainerBomFtvSectionSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitContainerNodeSettingTreeViewSplitterDistance {
            get {
                return ((int)(this["splitContainerNodeSettingTreeViewSplitterDistance"]));
            }
            set {
                this["splitContainerNodeSettingTreeViewSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitContainerHorizontalBomManagementSplitterDistance {
            get {
                return ((int)(this["splitContainerHorizontalBomManagementSplitterDistance"]));
            }
            set {
                this["splitContainerHorizontalBomManagementSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Resources\\HTML pages\\")]
        public string ApplicationDefaultHtmlPages {
            get {
                return ((string)(this["ApplicationDefaultHtmlPages"]));
            }
            set {
                this["ApplicationDefaultHtmlPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BarCodeDevices {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BarCodeDevices"]));
            }
            set {
                this["BarCodeDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationsShowDataBaseUpDate {
            get {
                return ((bool)(this["NotificationsShowDataBaseUpDate"]));
            }
            set {
                this["NotificationsShowDataBaseUpDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationsShowEmails {
            get {
                return ((bool)(this["NotificationsShowEmails"]));
            }
            set {
                this["NotificationsShowEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveEachTimeTheInformationIsChanged {
            get {
                return ((bool)(this["SaveEachTimeTheInformationIsChanged"]));
            }
            set {
                this["SaveEachTimeTheInformationIsChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveTheInformationByTime {
            get {
                return ((bool)(this["SaveTheInformationByTime"]));
            }
            set {
                this["SaveTheInformationByTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveTheInformationWhenTheUserSave {
            get {
                return ((bool)(this["SaveTheInformationWhenTheUserSave"]));
            }
            set {
                this["SaveTheInformationWhenTheUserSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Every5minutes {
            get {
                return ((bool)(this["Every5minutes"]));
            }
            set {
                this["Every5minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Every15minutes {
            get {
                return ((bool)(this["Every15minutes"]));
            }
            set {
                this["Every15minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Every30minutes {
            get {
                return ((bool)(this["Every30minutes"]));
            }
            set {
                this["Every30minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime InstallationFirstDate {
            get {
                return ((global::System.DateTime)(this["InstallationFirstDate"]));
            }
            set {
                this["InstallationFirstDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationFirstUser {
            get {
                return ((string)(this["InstallationFirstUser"]));
            }
            set {
                this["InstallationFirstUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int IntervalReadingNotifications {
            get {
                return ((int)(this["IntervalReadingNotifications"]));
            }
            set {
                this["IntervalReadingNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int IntervalTrackBar_Value {
            get {
                return ((int)(this["IntervalTrackBar_Value"]));
            }
            set {
                this["IntervalTrackBar_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("seconds")]
        public string IntervalTimeUnitName {
            get {
                return ((string)(this["IntervalTimeUnitName"]));
            }
            set {
                this["IntervalTimeUnitName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenameDistFileName {
            get {
                return ((bool)(this["RenameDistFileName"]));
            }
            set {
                this["RenameDistFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteOriginalFile {
            get {
                return ((bool)(this["DeleteOriginalFile"]));
            }
            set {
                this["DeleteOriginalFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SpeechSynthesizerBaseVolume {
            get {
                return ((int)(this["SpeechSynthesizerBaseVolume"]));
            }
            set {
                this["SpeechSynthesizerBaseVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpeechSynthesizerBaseRate {
            get {
                return ((int)(this["SpeechSynthesizerBaseRate"]));
            }
            set {
                this["SpeechSynthesizerBaseRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataGridViewDrawDoubleBuffering {
            get {
                return ((bool)(this["DataGridViewDrawDoubleBuffering"]));
            }
            set {
                this["DataGridViewDrawDoubleBuffering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-36865")]
        public int DataGridViewDrawSelectedColor {
            get {
                return ((int)(this["DataGridViewDrawSelectedColor"]));
            }
            set {
                this["DataGridViewDrawSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DocumentationBehavior {
            get {
                return ((int)(this["DocumentationBehavior"]));
            }
            set {
                this["DocumentationBehavior"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inch")]
        public string PdfReportUnitOfMeasure {
            get {
                return ((string)(this["PdfReportUnitOfMeasure"]));
            }
            set {
                this["PdfReportUnitOfMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5x11, 8.5x14, 11x17, 12x18")]
        public string PdfReportPaperSizeList {
            get {
                return ((string)(this["PdfReportPaperSizeList"]));
            }
            set {
                this["PdfReportPaperSizeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportMinimumWidthMargin {
            get {
                return ((string)(this["PdfReportMinimumWidthMargin"]));
            }
            set {
                this["PdfReportMinimumWidthMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportMaximumLeftMargin {
            get {
                return ((string)(this["PdfReportMaximumLeftMargin"]));
            }
            set {
                this["PdfReportMaximumLeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportMaximumRightMargin {
            get {
                return ((string)(this["PdfReportMaximumRightMargin"]));
            }
            set {
                this["PdfReportMaximumRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportTopMargin {
            get {
                return ((string)(this["PdfReportTopMargin"]));
            }
            set {
                this["PdfReportTopMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportButtomMargin {
            get {
                return ((string)(this["PdfReportButtomMargin"]));
            }
            set {
                this["PdfReportButtomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string PdfReportTitleFontName {
            get {
                return ((string)(this["PdfReportTitleFontName"]));
            }
            set {
                this["PdfReportTitleFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.0")]
        public string PdfReportTitleFontSize {
            get {
                return ((string)(this["PdfReportTitleFontSize"]));
            }
            set {
                this["PdfReportTitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string PdfReportTitleFontBold {
            get {
                return ((string)(this["PdfReportTitleFontBold"]));
            }
            set {
                this["PdfReportTitleFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string PdfReportHeaderFontName {
            get {
                return ((string)(this["PdfReportHeaderFontName"]));
            }
            set {
                this["PdfReportHeaderFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
        public string PdfReportHeaderFontSize {
            get {
                return ((string)(this["PdfReportHeaderFontSize"]));
            }
            set {
                this["PdfReportHeaderFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string PdfReportHeaderFontBold {
            get {
                return ((string)(this["PdfReportHeaderFontBold"]));
            }
            set {
                this["PdfReportHeaderFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string PdfReportHeaderOnEachPage {
            get {
                return ((string)(this["PdfReportHeaderOnEachPage"]));
            }
            set {
                this["PdfReportHeaderOnEachPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VeryLightBlue")]
        public string PdfReportHeaderBackgroudColor {
            get {
                return ((string)(this["PdfReportHeaderBackgroudColor"]));
            }
            set {
                this["PdfReportHeaderBackgroudColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string PdfReportBodyFontName {
            get {
                return ((string)(this["PdfReportBodyFontName"]));
            }
            set {
                this["PdfReportBodyFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
        public string PdfReportBodyFontSize {
            get {
                return ((string)(this["PdfReportBodyFontSize"]));
            }
            set {
                this["PdfReportBodyFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.15")]
        public string PdfReportBoldSizeFactor {
            get {
                return ((string)(this["PdfReportBoldSizeFactor"]));
            }
            set {
                this["PdfReportBoldSizeFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportHeaderMarginHorizontal {
            get {
                return ((string)(this["PdfReportHeaderMarginHorizontal"]));
            }
            set {
                this["PdfReportHeaderMarginHorizontal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportHeaderMarginVertical {
            get {
                return ((string)(this["PdfReportHeaderMarginVertical"]));
            }
            set {
                this["PdfReportHeaderMarginVertical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportCellMarginHorizontal {
            get {
                return ((string)(this["PdfReportCellMarginHorizontal"]));
            }
            set {
                this["PdfReportCellMarginHorizontal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportCellMarginVertical {
            get {
                return ((string)(this["PdfReportCellMarginVertical"]));
            }
            set {
                this["PdfReportCellMarginVertical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PdfReportJustifyPageWide {
            get {
                return ((string)(this["PdfReportJustifyPageWide"]));
            }
            set {
                this["PdfReportJustifyPageWide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VeryLightGray")]
        public string PdfReportAlternativeRowBackgroudColor {
            get {
                return ((string)(this["PdfReportAlternativeRowBackgroudColor"]));
            }
            set {
                this["PdfReportAlternativeRowBackgroudColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PdfReportShowRowHotizontalLine {
            get {
                return ((string)(this["PdfReportShowRowHotizontalLine"]));
            }
            set {
                this["PdfReportShowRowHotizontalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public string PdfReportCellLineWidth {
            get {
                return ((string)(this["PdfReportCellLineWidth"]));
            }
            set {
                this["PdfReportCellLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public string PdfReportCellLineColor {
            get {
                return ((string)(this["PdfReportCellLineColor"]));
            }
            set {
                this["PdfReportCellLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public string PdfReportGroupHeaderLineWidth {
            get {
                return ((string)(this["PdfReportGroupHeaderLineWidth"]));
            }
            set {
                this["PdfReportGroupHeaderLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VeryDarkGray")]
        public string PdfReportGroupHeaderLineColor {
            get {
                return ((string)(this["PdfReportGroupHeaderLineColor"]));
            }
            set {
                this["PdfReportGroupHeaderLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VeryLightYellow")]
        public string PdfReportGroupHeaderBackgroudColor {
            get {
                return ((string)(this["PdfReportGroupHeaderBackgroudColor"]));
            }
            set {
                this["PdfReportGroupHeaderBackgroudColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PdfReportShowGroupRowHotizontalLine {
            get {
                return ((string)(this["PdfReportShowGroupRowHotizontalLine"]));
            }
            set {
                this["PdfReportShowGroupRowHotizontalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportFrameWidth {
            get {
                return ((string)(this["PdfReportFrameWidth"]));
            }
            set {
                this["PdfReportFrameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0")]
        public string PdfReportGridWidth {
            get {
                return ((string)(this["PdfReportGridWidth"]));
            }
            set {
                this["PdfReportGridWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PdfReport1 {
            get {
                return ((string)(this["PdfReport1"]));
            }
            set {
                this["PdfReport1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PdfReport2 {
            get {
                return ((string)(this["PdfReport2"]));
            }
            set {
                this["PdfReport2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03,04,")]
        public string ASCII_Control_Characters {
            get {
                return ((string)(this["ASCII_Control_Characters"]));
            }
            set {
                this["ASCII_Control_Characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSuperPeer {
            get {
                return ((bool)(this["IsSuperPeer"]));
            }
            set {
                this["IsSuperPeer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Resources\\Ngrok\\ngrok.exe")]
        public string NgrokUtilityPath {
            get {
                return ((string)(this["NgrokUtilityPath"]));
            }
            set {
                this["NgrokUtilityPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.0")]
        public decimal ZebraPrintsDarknessValue {
            get {
                return ((decimal)(this["ZebraPrintsDarknessValue"]));
            }
            set {
                this["ZebraPrintsDarknessValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right Click and select \'Remove this Filter\' to clear that selection.")]
        public string RightClickRemoveFilter {
            get {
                return ((string)(this["RightClickRemoveFilter"]));
            }
            set {
                this["RightClickRemoveFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is an external Filter, there is no action to clear that selection.")]
        public string ThisIsAnExternalFilter {
            get {
                return ((string)(this["ThisIsAnExternalFilter"]));
            }
            set {
                this["ThisIsAnExternalFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There is no Filter to clear at this moment.")]
        public string ThereIsnoFiltertoClear {
            get {
                return ((string)(this["ThereIsnoFiltertoClear"]));
            }
            set {
                this["ThereIsnoFiltertoClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error in External Filter.")]
        public string ErrorInExternalFilter {
            get {
                return ((string)(this["ErrorInExternalFilter"]));
            }
            set {
                this["ErrorInExternalFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProcessSearchByClick(), Search engine has generated an error.")]
        public string ProcessSearchByClickHasgeneratedanerror {
            get {
                return ((string)(this["ProcessSearchByClickHasgeneratedanerror"]));
            }
            set {
                this["ProcessSearchByClickHasgeneratedanerror"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search engine has generated an error.")]
        public string SearchEngineHasGeneratedAnError {
            get {
                return ((string)(this["SearchEngineHasGeneratedAnError"]));
            }
            set {
                this["SearchEngineHasGeneratedAnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USBDeviceCollection {
            get {
                return ((string)(this["USBDeviceCollection"]));
            }
            set {
                this["USBDeviceCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PdfViewer {
            get {
                return ((bool)(this["PdfViewer"]));
            }
            set {
                this["PdfViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=D:\\ProductionManagement\\ProductionInventory.sqlite;")]
        public string DataBaseConnectionStringSQLite {
            get {
                return ((string)(this["DataBaseConnectionStringSQLite"]));
            }
            set {
                this["DataBaseConnectionStringSQLite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DRIVERRESOURCE_NOTFOUND {
            get {
                return ((string)(this["DRIVERRESOURCE_NOTFOUND"]));
            }
            set {
                this["DRIVERRESOURCE_NOTFOUND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This device is connected and does not currently have a device driver (driverless)" +
            ". Install this driver now to start using it right away.")]
        public string INSTALLDRIVER_DRIVERLESS_TEXT {
            get {
                return ((string)(this["INSTALLDRIVER_DRIVERLESS_TEXT"]));
            }
            set {
                this["INSTALLDRIVER_DRIVERLESS_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Driver installation failed, check log for details.")]
        public string INSTALLDRIVER_FAILED {
            get {
                return ((string)(this["INSTALLDRIVER_FAILED"]));
            }
            set {
                this["INSTALLDRIVER_FAILED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A setup package must be generated and drivers must be spawned to use the driver i" +
            "nstaller feature.")]
        public string INSTALLDRIVER_NOPACKAGE_TEXT {
            get {
                return ((string)(this["INSTALLDRIVER_NOPACKAGE_TEXT"]));
            }
            set {
                this["INSTALLDRIVER_NOPACKAGE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The driver was successfully installed.")]
        public string INSTALLDRIVER_SUCCESS {
            get {
                return ((string)(this["INSTALLDRIVER_SUCCESS"]));
            }
            set {
                this["INSTALLDRIVER_SUCCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One or more devices using a {0} service are already installed. The current driver" +
            "s should be removed before installing this package.")]
        public string INSTALLDRIVER_UPDATE_TEXT {
            get {
                return ((string)(this["INSTALLDRIVER_UPDATE_TEXT"]));
            }
            set {
                this["INSTALLDRIVER_UPDATE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One or more devices using a {0} service are already installed.  This package may " +
            "cause system crashes or blue screens if used!")]
        public string INSTALLDRIVER_WINDOWSSERVICE_TEXT {
            get {
                return ((string)(this["INSTALLDRIVER_WINDOWSSERVICE_TEXT"]));
            }
            set {
                this["INSTALLDRIVER_WINDOWSSERVICE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
            "/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html xmlns=\"http://www.w3.org/1999/" +
            "xhtml\">\r\n<head>\r\n    <title>#DEVICE_DESCRIPTION# USB setup package</title>\r\n    " +
            "<style type=\"text/css\">\r\n<!--\r\nbody {\r\n\tfont-family: Tahoma, Verdana, Arial;\r\n\tf" +
            "ont-size:12px;\r\n}\r\n.title {\r\n\tfont-weight:bold;\r\n\ttext-align:center;\r\n\tfont-size" +
            ":150%;\r\n}\r\n.copyright {\r\n\tfont-weight:normal;\r\n\ttext-align:center;\r\n\tfont-size:8" +
            "0%;\r\n\ttext-transform:capitalize;\r\n}\r\ntable.info td{\r\n\tborder-bottom-style: solid" +
            ";\r\n\tborder-bottom-color: #C8CDDE;\r\n\tborder-bottom-width: 1px;\r\n\tbackground: #F7F" +
            "7FF;\r\n\tpadding: 0.2em;\r\n\tvertical-align: top;\r\n\toverflow: hidden;\r\n}\r\n-->\r\n    <" +
            "/style>\r\n</head>\r\n<body>\r\n<table><tr><td>\r\n    <div class=\"title\">#DEVICE_DESCRI" +
            "PTION# USB setup package</div>\r\n    <div class=\"copyright\">generated by LibUsbDo" +
            "tNet InfWizard&#169;</div>\r\n    <br/>\r\n    <table class=\"info\">\r\n        <tr><td" +
            ">Driver Resource</td><td>#DisplayName#</td></tr>\r\n        <tr><td>VID / PID</td>" +
            "<td>#VID# / #PID# (#HARDWAREID#)</td></tr>\r\n        <tr><td>Manufacturer</td><td" +
            ">#DEVICE_MANUFACTURER#</td></tr>\r\n        <tr><td>Description</td><td>#DEVICE_DE" +
            "SCRIPTION#</td></tr>\r\n        <tr><td>Driver Date</td><td>#DRIVER_DATE#</td></tr" +
            ">\r\n        <tr><td>Driver Version</td><td>#DRIVER_VERSION#</td></tr>\r\n        <t" +
            "r><td>DeviceInterfaceGUID</td><td>#DEVICE_INTERFACE_GUID#</td></tr>\r\n    </table" +
            ">\r\n    <hr />\r\n    <div><pre>#Description#</pre></div>\r\n    </td></tr></table>\r\n" +
            "</body>\r\n</html>")]
        public string SETUP_PACKAGE_README_HTM {
            get {
                return ((string)(this["SETUP_PACKAGE_README_HTM"]));
            }
            set {
                this["SETUP_PACKAGE_README_HTM"] = value;
            }
        }
    }
}
