namespace MyStuff11net
{
    partial class Heatsink
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            groupBox1 = new System.Windows.Forms.GroupBox();
            label_Description = new System.Windows.Forms.Label();
    //        numericHeight = new AMS.TextBox.NumericTextBox();
            label_Height_Heatsinks = new System.Windows.Forms.Label();
    //        numericWidth = new AMS.TextBox.NumericTextBox();
    //        numericLength = new AMS.TextBox.NumericTextBox();
            label_Package_Cooled_Heatsinks = new System.Windows.Forms.Label();
            Package_Cooled = new System.Windows.Forms.ComboBox();
            Attachment_Method = new System.Windows.Forms.ComboBox();
            Power_Dissipation = new System.Windows.Forms.TextBox();
            label_AutoGenerated_Description_Heatsinks = new System.Windows.Forms.Label();
            label_Width_Heatsinks = new System.Windows.Forms.Label();
            label_Length_Heatsinks = new System.Windows.Forms.Label();
            label_Attachment_Method_Heatsinks = new System.Windows.Forms.Label();
            label_Power_Dissipation_Heatsinks = new System.Windows.Forms.Label();
            groupBox1.SuspendLayout();
            SuspendLayout();
            // 
            // groupBox1
            // 
            groupBox1.Controls.Add(label_Description);
     //       groupBox1.Controls.Add(numericHeight);
            groupBox1.Controls.Add(label_Height_Heatsinks);
     //       groupBox1.Controls.Add(numericWidth);
    //        groupBox1.Controls.Add(numericLength);
            groupBox1.Controls.Add(label_Package_Cooled_Heatsinks);
            groupBox1.Controls.Add(Package_Cooled);
            groupBox1.Controls.Add(Attachment_Method);
            groupBox1.Controls.Add(Power_Dissipation);
            groupBox1.Controls.Add(label_AutoGenerated_Description_Heatsinks);
            groupBox1.Controls.Add(label_Width_Heatsinks);
            groupBox1.Controls.Add(label_Length_Heatsinks);
            groupBox1.Controls.Add(label_Attachment_Method_Heatsinks);
            groupBox1.Controls.Add(label_Power_Dissipation_Heatsinks);
            groupBox1.Dock = System.Windows.Forms.DockStyle.Top;
            groupBox1.Location = new System.Drawing.Point(0, 0);
            groupBox1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 5);
            groupBox1.Name = "groupBox1";
            groupBox1.Padding = new System.Windows.Forms.Padding(8, 5, 5, 8);
            groupBox1.Size = new System.Drawing.Size(600, 114);
            groupBox1.TabIndex = 35;
            groupBox1.TabStop = false;
            groupBox1.Tag = "Heatsink";
            groupBox1.Text = "Heatsink";
            // 
            // label_Description
            // 
            label_Description.AutoSize = true;
            label_Description.Dock = System.Windows.Forms.DockStyle.Bottom;
            label_Description.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Description.Location = new System.Drawing.Point(8, 89);
            label_Description.Name = "label_Description";
            label_Description.Size = new System.Drawing.Size(344, 17);
            label_Description.TabIndex = 66;
            label_Description.Text = "012345678910123456789012345678901234567890";
            label_Description.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // numericHeight
            /*
            numericHeight.AllowNegative = false;
            numericHeight.DigitsInGroup = 0;
            numericHeight.Flags = 65536;
            numericHeight.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            numericHeight.Location = new System.Drawing.Point(534, 32);
            numericHeight.MaxDecimalPlaces = 3;
            numericHeight.MaxLength = 6;
            numericHeight.MaxWholeDigits = 9;
            numericHeight.Name = "numericHeight";
            numericHeight.Prefix = "";
            numericHeight.RangeMax = 1.7976931348623157E+308D;
            numericHeight.RangeMin = -1.7976931348623157E+308D;
            numericHeight.Size = new System.Drawing.Size(50, 26);
            numericHeight.TabIndex = 65;
            numericHeight.Text = "0.000";
            numericHeight.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            numericHeight.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            numericHeight.Leave += new System.EventHandler(Any_Leave);
            */ 
            // label_Height_Heatsinks
            // 
            label_Height_Heatsinks.AutoSize = true;
            label_Height_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Height_Heatsinks.Location = new System.Drawing.Point(533, 15);
            label_Height_Heatsinks.Name = "label_Height_Heatsinks";
            label_Height_Heatsinks.Size = new System.Drawing.Size(44, 13);
            label_Height_Heatsinks.TabIndex = 64;
            label_Height_Heatsinks.Text = "Height";
            // 
            // numericWidth
            /* 
            numericWidth.AllowNegative = false;
            numericWidth.DigitsInGroup = 0;
            numericWidth.Flags = 65536;
            numericWidth.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            numericWidth.Location = new System.Drawing.Point(478, 32);
            numericWidth.MaxDecimalPlaces = 3;
            numericWidth.MaxLength = 6;
            numericWidth.MaxWholeDigits = 9;
            numericWidth.Name = "numericWidth";
            numericWidth.Prefix = "";
            numericWidth.RangeMax = 1.7976931348623157E+308D;
            numericWidth.RangeMin = -1.7976931348623157E+308D;
            numericWidth.Size = new System.Drawing.Size(50, 26);
            numericWidth.TabIndex = 63;
            numericWidth.Text = "0.000";
            numericWidth.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            numericWidth.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            numericWidth.Leave += new System.EventHandler(Any_Leave);
            */ 
            // numericLength
            /* 
            numericLength.AllowNegative = false;
            numericLength.DigitsInGroup = 0;
            numericLength.Flags = 65536;
            numericLength.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            numericLength.Location = new System.Drawing.Point(422, 32);
            numericLength.MaxDecimalPlaces = 3;
            numericLength.MaxLength = 6;
            numericLength.MaxWholeDigits = 9;
            numericLength.Name = "numericLength";
            numericLength.Prefix = "";
            numericLength.RangeMax = 1.7976931348623157E+308D;
            numericLength.RangeMin = -1.7976931348623157E+308D;
            numericLength.Size = new System.Drawing.Size(50, 26);
            numericLength.TabIndex = 62;
            numericLength.Text = "0.000";
            numericLength.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            numericLength.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            numericLength.Leave += new System.EventHandler(Any_Leave);
            */ 
            // label_Package_Cooled_Heatsinks
            // 
            label_Package_Cooled_Heatsinks.AutoSize = true;
            label_Package_Cooled_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Package_Cooled_Heatsinks.Location = new System.Drawing.Point(183, 16);
            label_Package_Cooled_Heatsinks.Name = "label_Package_Cooled_Heatsinks";
            label_Package_Cooled_Heatsinks.Size = new System.Drawing.Size(100, 13);
            label_Package_Cooled_Heatsinks.TabIndex = 20;
            label_Package_Cooled_Heatsinks.Text = "Package Cooled";
            // 
            // Package_Cooled
            // 
            Package_Cooled.DisplayMember = "TO-263";
            Package_Cooled.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Package_Cooled.FormattingEnabled = true;
            Package_Cooled.Items.AddRange(new object[] {
            "TO-220",
            "TO-220 (Dual)",
            "TO-262",
            "TO-263 (DPack)"});
            Package_Cooled.Location = new System.Drawing.Point(186, 33);
            Package_Cooled.Name = "Package_Cooled";
            Package_Cooled.Size = new System.Drawing.Size(129, 24);
            Package_Cooled.TabIndex = 19;
            Package_Cooled.Text = "TO-263 (DPack)";
            Package_Cooled.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Package_Cooled.Leave += new System.EventHandler(Any_Leave);
            // 
            // Attachment_Method
            // 
            Attachment_Method.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Attachment_Method.FormattingEnabled = true;
            Attachment_Method.Items.AddRange(new object[] {
            "Clip",
            "PC Pin",
            "Bolt On",
            "Slide On",
            "Press Fit",
            "SMD Pad"});
            Attachment_Method.Location = new System.Drawing.Point(321, 33);
            Attachment_Method.Name = "Attachment_Method";
            Attachment_Method.Size = new System.Drawing.Size(90, 24);
            Attachment_Method.TabIndex = 16;
            Attachment_Method.Text = "SMD Pad";
            Attachment_Method.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Attachment_Method.Leave += new System.EventHandler(Any_Leave);
            // 
            // Power_Dissipation
            // 
            Power_Dissipation.BorderStyle = System.Windows.Forms.BorderStyle.None;
            Power_Dissipation.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Power_Dissipation.Location = new System.Drawing.Point(12, 34);
            Power_Dissipation.Name = "Power_Dissipation";
            Power_Dissipation.Size = new System.Drawing.Size(168, 23);
            Power_Dissipation.TabIndex = 15;
            Power_Dissipation.Text = "1.25 watts @ 30 C";
            Power_Dissipation.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Power_Dissipation.Leave += new System.EventHandler(Any_Leave);
            // 
            // label_AutoGenerated_Description_Heatsinks
            // 
            label_AutoGenerated_Description_Heatsinks.AutoSize = true;
            label_AutoGenerated_Description_Heatsinks.Location = new System.Drawing.Point(9, 73);
            label_AutoGenerated_Description_Heatsinks.Name = "label_AutoGenerated_Description_Heatsinks";
            label_AutoGenerated_Description_Heatsinks.Size = new System.Drawing.Size(135, 13);
            label_AutoGenerated_Description_Heatsinks.TabIndex = 14;
            label_AutoGenerated_Description_Heatsinks.Text = "AutoGenerated Description";
            // 
            // label_Width_Heatsinks
            // 
            label_Width_Heatsinks.AutoSize = true;
            label_Width_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Width_Heatsinks.Location = new System.Drawing.Point(478, 15);
            label_Width_Heatsinks.Name = "label_Width_Heatsinks";
            label_Width_Heatsinks.Size = new System.Drawing.Size(54, 13);
            label_Width_Heatsinks.TabIndex = 11;
            label_Width_Heatsinks.Text = "Width  x";
            // 
            // label_Length_Heatsinks
            // 
            label_Length_Heatsinks.AutoSize = true;
            label_Length_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Length_Heatsinks.Location = new System.Drawing.Point(418, 15);
            label_Length_Heatsinks.Name = "label_Length_Heatsinks";
            label_Length_Heatsinks.Size = new System.Drawing.Size(60, 13);
            label_Length_Heatsinks.TabIndex = 9;
            label_Length_Heatsinks.Text = "Length  x";
            // 
            // label_Attachment_Method_Heatsinks
            // 
            label_Attachment_Method_Heatsinks.AutoSize = true;
            label_Attachment_Method_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Attachment_Method_Heatsinks.Location = new System.Drawing.Point(321, 15);
            label_Attachment_Method_Heatsinks.Name = "label_Attachment_Method_Heatsinks";
            label_Attachment_Method_Heatsinks.Size = new System.Drawing.Size(90, 13);
            label_Attachment_Method_Heatsinks.TabIndex = 7;
            label_Attachment_Method_Heatsinks.Text = "Attach Method";
            // 
            // label_Power_Dissipation_Heatsinks
            // 
            label_Power_Dissipation_Heatsinks.AutoSize = true;
            label_Power_Dissipation_Heatsinks.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Power_Dissipation_Heatsinks.Location = new System.Drawing.Point(14, 18);
            label_Power_Dissipation_Heatsinks.Name = "label_Power_Dissipation_Heatsinks";
            label_Power_Dissipation_Heatsinks.Size = new System.Drawing.Size(108, 13);
            label_Power_Dissipation_Heatsinks.TabIndex = 4;
            label_Power_Dissipation_Heatsinks.Text = "Power Dissipation";
            // 
            // Heatsink
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Controls.Add(groupBox1);
            Name = "Heatsink";
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label_Description;
   //     private AMS.TextBox.NumericTextBox numericHeight;
        private System.Windows.Forms.Label label_Height_Heatsinks;
   //     private AMS.TextBox.NumericTextBox numericWidth;
  //      private AMS.TextBox.NumericTextBox numericLength;
        private System.Windows.Forms.Label label_Package_Cooled_Heatsinks;
        private System.Windows.Forms.ComboBox Package_Cooled;
        private System.Windows.Forms.ComboBox Attachment_Method;
        private System.Windows.Forms.TextBox Power_Dissipation;
        private System.Windows.Forms.Label label_AutoGenerated_Description_Heatsinks;
        private System.Windows.Forms.Label label_Width_Heatsinks;
        private System.Windows.Forms.Label label_Length_Heatsinks;
        private System.Windows.Forms.Label label_Attachment_Method_Heatsinks;
        private System.Windows.Forms.Label label_Power_Dissipation_Heatsinks;
    }
}
