namespace MyStuff11net
{
    partial class ManualsWarrantyCards
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            groupBox_ManualsWarrantyCars = new System.Windows.Forms.GroupBox();
            label_Description = new System.Windows.Forms.Label();
            label96 = new System.Windows.Forms.Label();
            Unid = new System.Windows.Forms.ComboBox();
            Package = new System.Windows.Forms.ComboBox();
            Power = new System.Windows.Forms.ComboBox();
            Tolerance = new System.Windows.Forms.ComboBox();
            Value = new System.Windows.Forms.TextBox();
            label_AutoGenerated_Description_Manuals = new System.Windows.Forms.Label();
            label98 = new System.Windows.Forms.Label();
            label99 = new System.Windows.Forms.Label();
            label100 = new System.Windows.Forms.Label();
            label101 = new System.Windows.Forms.Label();
            groupBox_ManualsWarrantyCars.SuspendLayout();
            SuspendLayout();
            // 
            // groupBox_ManualsWarrantyCars
            // 
            groupBox_ManualsWarrantyCars.Controls.Add(label_Description);
            groupBox_ManualsWarrantyCars.Controls.Add(label96);
            groupBox_ManualsWarrantyCars.Controls.Add(Unid);
            groupBox_ManualsWarrantyCars.Controls.Add(Package);
            groupBox_ManualsWarrantyCars.Controls.Add(Power);
            groupBox_ManualsWarrantyCars.Controls.Add(Tolerance);
            groupBox_ManualsWarrantyCars.Controls.Add(Value);
            groupBox_ManualsWarrantyCars.Controls.Add(label_AutoGenerated_Description_Manuals);
            groupBox_ManualsWarrantyCars.Controls.Add(label98);
            groupBox_ManualsWarrantyCars.Controls.Add(label99);
            groupBox_ManualsWarrantyCars.Controls.Add(label100);
            groupBox_ManualsWarrantyCars.Controls.Add(label101);
            groupBox_ManualsWarrantyCars.Dock = System.Windows.Forms.DockStyle.Top;
            groupBox_ManualsWarrantyCars.Location = new System.Drawing.Point(0, 0);
            groupBox_ManualsWarrantyCars.Margin = new System.Windows.Forms.Padding(3, 3, 3, 5);
            groupBox_ManualsWarrantyCars.Name = "groupBox_ManualsWarrantyCars";
            groupBox_ManualsWarrantyCars.Padding = new System.Windows.Forms.Padding(8, 5, 5, 8);
            groupBox_ManualsWarrantyCars.Size = new System.Drawing.Size(600, 114);
            groupBox_ManualsWarrantyCars.TabIndex = 50;
            groupBox_ManualsWarrantyCars.TabStop = false;
            groupBox_ManualsWarrantyCars.Tag = "ManualsWarrantyCars";
            groupBox_ManualsWarrantyCars.Text = "ManualsWarrantyCars";
            // 
            // label_Description
            // 
            label_Description.AutoSize = true;
            label_Description.Dock = System.Windows.Forms.DockStyle.Bottom;
            label_Description.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Description.Location = new System.Drawing.Point(8, 89);
            label_Description.Name = "label_Description";
            label_Description.Size = new System.Drawing.Size(344, 17);
            label_Description.TabIndex = 67;
            label_Description.Text = "012345678910123456789012345678901234567890";
            label_Description.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label96
            // 
            label96.AutoSize = true;
            label96.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label96.Location = new System.Drawing.Point(78, 16);
            label96.Name = "label96";
            label96.Size = new System.Drawing.Size(33, 13);
            label96.TabIndex = 20;
            label96.Text = "Unid";
            // 
            // Unid
            // 
            Unid.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Unid.FormattingEnabled = true;
            Unid.Location = new System.Drawing.Point(74, 32);
            Unid.Name = "Unid";
            Unid.Size = new System.Drawing.Size(83, 26);
            Unid.TabIndex = 19;
            Unid.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Unid.Leave += new System.EventHandler(Any_Leave);
            // 
            // Package
            // 
            Package.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Package.FormattingEnabled = true;
            Package.Items.AddRange(new object[] {
            "0402",
            "0603",
            "0805",
            "1008",
            "1206",
            "1210",
            "1411",
            "1612",
            "1806",
            "1812",
            "1913",
            "2010",
            "2225",
            "2412",
            "2416",
            "2512",
            "2916",
            "3119",
            "3312",
            "Through"});
            Package.Location = new System.Drawing.Point(336, 34);
            Package.Name = "Package";
            Package.Size = new System.Drawing.Size(64, 26);
            Package.TabIndex = 18;
            Package.Text = "0402";
            Package.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Package.Leave += new System.EventHandler(Any_Leave);
            // 
            // Power
            // 
            Power.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Power.FormattingEnabled = true;
            Power.Items.AddRange(new object[] {
            "1/8 W",
            "1/4 W",
            "1/2 W",
            "3/8 W",
            "1 W",
            "1.5 W",
            "2 W",
            "5 W",
            "10 W",
            "20 W"});
            Power.Location = new System.Drawing.Point(255, 33);
            Power.Name = "Power";
            Power.Size = new System.Drawing.Size(64, 26);
            Power.TabIndex = 17;
            Power.Text = "1/8 W";
            Power.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Power.Leave += new System.EventHandler(Any_Leave);
            // 
            // Tolerance
            // 
            Tolerance.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Tolerance.FormattingEnabled = true;
            Tolerance.Items.AddRange(new object[] {
            "0.1 %",
            "1 %",
            "5 %"});
            Tolerance.Location = new System.Drawing.Point(174, 33);
            Tolerance.Name = "Tolerance";
            Tolerance.Size = new System.Drawing.Size(64, 26);
            Tolerance.TabIndex = 16;
            Tolerance.Text = "1 %";
            Tolerance.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Tolerance.Leave += new System.EventHandler(Any_Leave);
            // 
            // Value
            // 
            Value.BorderStyle = System.Windows.Forms.BorderStyle.None;
            Value.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Value.Location = new System.Drawing.Point(12, 34);
            Value.Name = "Value";
            Value.Size = new System.Drawing.Size(55, 23);
            Value.TabIndex = 15;
            Value.KeyUp += new System.Windows.Forms.KeyEventHandler(Any_KeyUp);
            Value.Leave += new System.EventHandler(Any_Leave);
            // 
            // label_AutoGenerated_Description_Manuals
            // 
            label_AutoGenerated_Description_Manuals.AutoSize = true;
            label_AutoGenerated_Description_Manuals.Location = new System.Drawing.Point(9, 73);
            label_AutoGenerated_Description_Manuals.Name = "label_AutoGenerated_Description_Manuals";
            label_AutoGenerated_Description_Manuals.Size = new System.Drawing.Size(135, 13);
            label_AutoGenerated_Description_Manuals.TabIndex = 14;
            label_AutoGenerated_Description_Manuals.Text = "AutoGenerated Description";
            // 
            // label98
            // 
            label98.AutoSize = true;
            label98.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label98.Location = new System.Drawing.Point(340, 18);
            label98.Name = "label98";
            label98.Size = new System.Drawing.Size(31, 13);
            label98.TabIndex = 11;
            label98.Text = "Size";
            // 
            // label99
            // 
            label99.AutoSize = true;
            label99.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label99.Location = new System.Drawing.Point(256, 18);
            label99.Name = "label99";
            label99.Size = new System.Drawing.Size(42, 13);
            label99.TabIndex = 9;
            label99.Text = "Power";
            // 
            // label100
            // 
            label100.AutoSize = true;
            label100.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label100.Location = new System.Drawing.Point(175, 18);
            label100.Name = "label100";
            label100.Size = new System.Drawing.Size(64, 13);
            label100.TabIndex = 7;
            label100.Text = "Tolerance";
            // 
            // label101
            // 
            label101.AutoSize = true;
            label101.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label101.Location = new System.Drawing.Point(14, 18);
            label101.Name = "label101";
            label101.Size = new System.Drawing.Size(39, 13);
            label101.TabIndex = 4;
            label101.Text = "Value";
            // 
            // ManualsWarrantyCards
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Controls.Add(groupBox_ManualsWarrantyCars);
            Name = "ManualsWarrantyCards";
            groupBox_ManualsWarrantyCars.ResumeLayout(false);
            groupBox_ManualsWarrantyCars.PerformLayout();
            ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox_ManualsWarrantyCars;
        private System.Windows.Forms.Label label_Description;
        private System.Windows.Forms.Label label96;
        private System.Windows.Forms.ComboBox Unid;
        private System.Windows.Forms.ComboBox Package;
        private System.Windows.Forms.ComboBox Power;
        private System.Windows.Forms.ComboBox Tolerance;
        private System.Windows.Forms.TextBox Value;
        private System.Windows.Forms.Label label_AutoGenerated_Description_Manuals;
        private System.Windows.Forms.Label label98;
        private System.Windows.Forms.Label label99;
        private System.Windows.Forms.Label label100;
        private System.Windows.Forms.Label label101;
    }
}
