namespace MyStuff11net
{
    partial class PCBs
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            groupBox_PCBs = new System.Windows.Forms.GroupBox();
            label_Description = new System.Windows.Forms.Label();
            label114 = new System.Windows.Forms.Label();
            Unid = new System.Windows.Forms.ComboBox();
            Package = new System.Windows.Forms.ComboBox();
            Power = new System.Windows.Forms.ComboBox();
            Tolerance = new System.Windows.Forms.ComboBox();
            Value = new System.Windows.Forms.TextBox();
            label_AutoGenerated_Description_PC_Boards = new System.Windows.Forms.Label();
            label116 = new System.Windows.Forms.Label();
            label117 = new System.Windows.Forms.Label();
            label118 = new System.Windows.Forms.Label();
            label119 = new System.Windows.Forms.Label();
            groupBox_PCBs.SuspendLayout();
            SuspendLayout();
            // 
            // groupBox_PCBs
            // 
            groupBox_PCBs.Controls.Add(label_Description);
            groupBox_PCBs.Controls.Add(label114);
            groupBox_PCBs.Controls.Add(Unid);
            groupBox_PCBs.Controls.Add(Package);
            groupBox_PCBs.Controls.Add(Power);
            groupBox_PCBs.Controls.Add(Tolerance);
            groupBox_PCBs.Controls.Add(Value);
            groupBox_PCBs.Controls.Add(label_AutoGenerated_Description_PC_Boards);
            groupBox_PCBs.Controls.Add(label116);
            groupBox_PCBs.Controls.Add(label117);
            groupBox_PCBs.Controls.Add(label118);
            groupBox_PCBs.Controls.Add(label119);
            groupBox_PCBs.Dock = System.Windows.Forms.DockStyle.Top;
            groupBox_PCBs.Location = new System.Drawing.Point(0, 0);
            groupBox_PCBs.Margin = new System.Windows.Forms.Padding(3, 3, 3, 5);
            groupBox_PCBs.Name = "groupBox_PCBs";
            groupBox_PCBs.Padding = new System.Windows.Forms.Padding(8, 5, 5, 8);
            groupBox_PCBs.Size = new System.Drawing.Size(600, 114);
            groupBox_PCBs.TabIndex = 53;
            groupBox_PCBs.TabStop = false;
            groupBox_PCBs.Tag = "PCBs";
            groupBox_PCBs.Text = "PCBs";
            // 
            // label_Description
            // 
            label_Description.AutoSize = true;
            label_Description.Dock = System.Windows.Forms.DockStyle.Bottom;
            label_Description.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label_Description.Location = new System.Drawing.Point(8, 89);
            label_Description.Name = "label_Description";
            label_Description.Size = new System.Drawing.Size(344, 17);
            label_Description.TabIndex = 67;
            label_Description.Text = "012345678910123456789012345678901234567890";
            label_Description.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label114
            // 
            label114.AutoSize = true;
            label114.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label114.Location = new System.Drawing.Point(78, 16);
            label114.Name = "label114";
            label114.Size = new System.Drawing.Size(33, 13);
            label114.TabIndex = 20;
            label114.Text = "Unid";
            // 
            // Unid
            // 
            Unid.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Unid.FormattingEnabled = true;
            Unid.Location = new System.Drawing.Point(74, 32);
            Unid.Name = "Unid";
            Unid.Size = new System.Drawing.Size(83, 26);
            Unid.TabIndex = 19;
            // 
            // Package
            // 
            Package.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Package.FormattingEnabled = true;
            Package.Items.AddRange(new object[] {
            "0402",
            "0603",
            "0805",
            "1008",
            "1206",
            "1210",
            "1411",
            "1612",
            "1806",
            "1812",
            "1913",
            "2010",
            "2225",
            "2412",
            "2416",
            "2512",
            "2916",
            "3119",
            "3312",
            "Through"});
            Package.Location = new System.Drawing.Point(336, 34);
            Package.Name = "Package";
            Package.Size = new System.Drawing.Size(64, 26);
            Package.TabIndex = 18;
            Package.Text = "0402";
            // 
            // Power
            // 
            Power.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Power.FormattingEnabled = true;
            Power.Items.AddRange(new object[] {
            "1/8 W",
            "1/4 W",
            "1/2 W",
            "3/8 W",
            "1 W",
            "1.5 W",
            "2 W",
            "5 W",
            "10 W",
            "20 W"});
            Power.Location = new System.Drawing.Point(255, 33);
            Power.Name = "Power";
            Power.Size = new System.Drawing.Size(64, 26);
            Power.TabIndex = 17;
            Power.Text = "1/8 W";
            // 
            // Tolerance
            // 
            Tolerance.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Tolerance.FormattingEnabled = true;
            Tolerance.Items.AddRange(new object[] {
            "0.1 %",
            "1 %",
            "5 %"});
            Tolerance.Location = new System.Drawing.Point(174, 33);
            Tolerance.Name = "Tolerance";
            Tolerance.Size = new System.Drawing.Size(64, 26);
            Tolerance.TabIndex = 16;
            Tolerance.Text = "1 %";
            // 
            // Value
            // 
            Value.BorderStyle = System.Windows.Forms.BorderStyle.None;
            Value.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            Value.Location = new System.Drawing.Point(12, 34);
            Value.Name = "Value";
            Value.Size = new System.Drawing.Size(55, 23);
            Value.TabIndex = 15;
            // 
            // label_AutoGenerated_Description_PC_Boards
            // 
            label_AutoGenerated_Description_PC_Boards.AutoSize = true;
            label_AutoGenerated_Description_PC_Boards.Location = new System.Drawing.Point(9, 73);
            label_AutoGenerated_Description_PC_Boards.Name = "label_AutoGenerated_Description_PC_Boards";
            label_AutoGenerated_Description_PC_Boards.Size = new System.Drawing.Size(135, 13);
            label_AutoGenerated_Description_PC_Boards.TabIndex = 14;
            label_AutoGenerated_Description_PC_Boards.Text = "AutoGenerated Description";
            // 
            // label116
            // 
            label116.AutoSize = true;
            label116.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label116.Location = new System.Drawing.Point(340, 18);
            label116.Name = "label116";
            label116.Size = new System.Drawing.Size(31, 13);
            label116.TabIndex = 11;
            label116.Text = "Size";
            // 
            // label117
            // 
            label117.AutoSize = true;
            label117.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label117.Location = new System.Drawing.Point(256, 18);
            label117.Name = "label117";
            label117.Size = new System.Drawing.Size(42, 13);
            label117.TabIndex = 9;
            label117.Text = "Power";
            // 
            // label118
            // 
            label118.AutoSize = true;
            label118.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label118.Location = new System.Drawing.Point(175, 18);
            label118.Name = "label118";
            label118.Size = new System.Drawing.Size(64, 13);
            label118.TabIndex = 7;
            label118.Text = "Tolerance";
            // 
            // label119
            // 
            label119.AutoSize = true;
            label119.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            label119.Location = new System.Drawing.Point(14, 18);
            label119.Name = "label119";
            label119.Size = new System.Drawing.Size(39, 13);
            label119.TabIndex = 4;
            label119.Text = "Value";
            // 
            // PCBs
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Controls.Add(groupBox_PCBs);
            Name = "PCBs";
            groupBox_PCBs.ResumeLayout(false);
            groupBox_PCBs.PerformLayout();
            ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox_PCBs;
        private System.Windows.Forms.Label label_Description;
        private System.Windows.Forms.Label label114;
        private System.Windows.Forms.ComboBox Unid;
        private System.Windows.Forms.ComboBox Package;
        private System.Windows.Forms.ComboBox Power;
        private System.Windows.Forms.ComboBox Tolerance;
        private System.Windows.Forms.TextBox Value;
        private System.Windows.Forms.Label label_AutoGenerated_Description_PC_Boards;
        private System.Windows.Forms.Label label116;
        private System.Windows.Forms.Label label117;
        private System.Windows.Forms.Label label118;
        private System.Windows.Forms.Label label119;
    }
}
