using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StockRoom11net.Data.Entities;

/// <summary>
/// Represents a tree view item in the application, which can be either a department or an employee. This class is designed
/// to be flexible and accommodate various properties related to the tree view, such as display information, filtering criteria,
/// and hierarchical relationships.
/// </summary>
public interface ITableBaseTreeView
{
    int Index { get; }

    int ID { get; }

    int? Parent_ID { get; }

    string Code { get; }

    string Range { get; }

    string Text_Name { get; }

    string Node_PDF { get; }

    string Node_Picture { get; }

    string Description_Short { get; }

    string Description_Expand { get; }

    string Image { get; }

    string String_Filter { get; }

    int? ItemCount { get; }

    string DateCreated { get; }

    string Created_by { get; }

    string AvailableDepartments { get; }

    string Properties { get; }

    string Message_String { get; }

    string Status { get; }

    DateTime DateCreatedAsDateTime { get; }

    List<string> AvailableDepartmentList { get; }

    bool IsEmployee { get; }

    bool IsDepartment { get; }
}

public class Table_Base_TreeView : ITableBaseTreeView
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This attribute indicates that the value of Index will be generated by the
                                                          // database (auto-incremented) when a new record is inserted.
                                                          // The default value of 0 is set here for clarity, but it will be overridden by
                                                          // the database when a new record is created.
    public int Index { get; set; } = 0; // Default value of 0 for Index, DB auto-assigns the value (autoincrement)

    [Required] // Assign a default value of 0 for ID, which can be overridden when creating instances of this class.
               // The [Required] attribute ensures that a value must be provided for ID, even though it's an int (which cannot be null).
               // This allows for a default value while still enforcing that it cannot be left at the default when creating an instance of the class.
    public int ID { get; set; } = 0;

    [Required] // Assign a default value of 75 for Parent_ID, which can be overridden when creating instances of this class.
               // The [Required] attribute ensures that a value must be provided for Parent_ID, even though it's nullable.
               // This allows for a default value while still enforcing that it cannot be left null when creating an instance of the class.
    public int? Parent_ID { get; set; } = 75;

    
    public string Code { get; set; } = "";

    public string Range { get; set; } = "";

    [Required] // Assign a default value of an empty string for Text_Name, which can be overridden when creating instances of this class.
               // The [Required] attribute ensures that a value must be provided for Text_Name, even though it's a string (which can be null).
               // This allows for a default value while still enforcing that it cannot be left null when creating an instance of the class.
    [DatabaseGenerated(DatabaseGeneratedOption.None)] // This attribute indicates that the value of Text_Name will not be generated by the
                                                      // database. App must supply the value explicitly.
    public string Text_Name { get; set; } = "";

    public string Node_PDF { get; set; } = "";

    public string Node_Picture { get; set; } = "";

    public string Description_Short { get; set; } = "";

    public string Description_Expand { get; set; } = "";

    public string Image { get; set; } = "";

    public string String_Filter { get; set; } = "";

    public int? ItemCount { get; set; } = 0;

    public int? ItemOpen { get; set; } = 0;

    /// <summary>
    /// Using string to store DateTime for simplicity. The DbContext will handle conversion to/from DateTime.
    /// By default, it initializes to the current date and time as a string. The format can be standardized in the DbContext converter.
    /// </summary>
    [Required] // Assign a default value of the current date and time as a string for DateCreated, which can be overridden when creating instances of this class.
               // The [Required] attribute ensures that a value must be provided for DateCreated, even though it's a string (which can be null).
               // This allows for a default value while still enforcing that it cannot be left null when creating an instance of the class.
    public string DateCreated { get; set; } = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

    [Required] // Assign a default value of an empty string for Created_by, which can be overridden when creating instances of this class.
               // The [Required] attribute ensures that a value must be provided for Created_by, even though it's a string (which can be null).
               // This allows for a default value while still enforcing that it cannot be left null when creating an instance of the class.
    public string Created_by { get; set; } = "";

    public string AvailableDepartments { get; set; } = "";

    public string Properties { get; set; } = "";

    public string Message_String { get; set; } = "";

    public string Status { get; set; } = "";

    /// <summary>
    /// Typed accessor for DateCreated.
    /// The value converter in DbContext handles string ↔ DateTime? conversion.
    /// </summary>
    [NotMapped]
    public DateTime DateCreatedAsDateTime
    {
        get => DateTime.TryParse(DateCreated, out var dt) ? dt : DateTime.Now;
        set => DateCreated = value.ToString("yyyy-MM-dd HH:mm:ss");
    }

    /// <summary>
    /// Gets or sets the list of available departments where this treeView menu is available.AvalaibleDepartments
    /// </summary>
    /// <remarks>When getting the property, the list is derived from the <c>Properties</c> string,
    /// which is expected to contain department information in a specific format. If the format is invalid or
    /// missing, a default list is returned, and the <c>Properties</c> string is updated accordingly.  When setting
    /// the property, the provided list of department names is serialized into the <c>Properties</c> string in the
    /// expected format.</remarks>
    [NotMapped]
    public List<string> AvailableDepartmentList
    {
        get
        {
            List<string> _listDepart = new List<string>();

            if (string.IsNullOrEmpty(AvailableDepartments))
                return _listDepart;

            var _strings = AvailableDepartments.Split(new char[] { ':', ';' }, StringSplitOptions.RemoveEmptyEntries);

            if (_strings.Length == 1)
            {
                _listDepart.Add("No set to any department yet");
                return _listDepart;
            }

            //"AvailableDepart:ToAll,StockRoom;Selected:false;Unerasable:true;Color:-36865;Note:Null;HeaderInf:Null;DisplayStatus:false,false,0"
            //      0            2             4                6            8        10             12
            if (_strings[0].Contains("AvailableDepart") && _strings.Length >= 2)
                _listDepart = _strings[1].Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList();
            else
            {
                AvailableDepartments = "AvailableDepart:ToAll,StockRoom;";
                _listDepart = "ToAll,StockRoom".Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList();
            }

            return _listDepart;
        }
        set
        {
            string listDepart = "AvailableDepart:";
            foreach (string depart in value)
            {
                listDepart += depart + ",";
            }
            listDepart = listDepart.TrimEnd(',');

            AvailableDepartments = listDepart;
        }
    }

    [NotMapped]
    public bool IsEmployee
    {
        get
        {
            if (String_Filter != null && String_Filter.Contains("Department NOT LIKE '*Department*'"))
                return true;
            else
                return false;
        }
    }

    [NotMapped]
    public bool IsDepartment
    {
        get
        {
            if (String_Filter.Contains("Department LIKE '*Department*'"))
                return true;
            else
                return false;
        }
    }

}
